### ISSUE TITLE
Integrate Appium Server into the Harness

### ISSUE THREAD

**Issue by nodlesh** [hyperledger/aries-mobile-test-harness#3]

**Comment by NB-MikeRichardson** [comment]
Also this issue can cover integration of Appium test framework with the Browserstack cloud test framework

**Comment by NB-MikeRichardson** [comment]
No need to integrate Appium server into the test harness as an appium server runs inside the BrowserStack cloud. The main focus of this issue should be to become familiar with the BrowserStack functionality in order to optimise the test runs. 

Whether there might be a case to be made for running local Appium servers in a development environment prior to running tests on BrowserStack remains to be seen. That might be useful as BS resources are paid for and it could save on cost (unless we have a free account of course), or perhaps for convenience.

I will go over the BrowserStack documentation and put any recommendations here.
